name: lecture_music
description: A Flutter application that converts lecture notes to music.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  file_picker: ^10.1.2
  http: ^1.3.0
  audioplayers: ^6.4.0
  path_provider: ^2.0.15
  flutter_file_dialog: ^3.0.2  # Alternative for desktop platforms

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/fonts/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
